name: Jest Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # 任意のバージョンを指定してください

    - name: Install dependencies
      run: |
        echo "yarn install"
        echo node version $(node -v)
        echo yarn version $(yarn -v)
        yarn install

    - name: Run Jest tests
      run: yarn jest
